########################################################################################################################
# View - settings
########################################################################################################################
title: Settings
icon: mdi:settings-outline
cards:
  - type: custom:compact-custom-header
  - type: custom:tracker-card
    title:
    trackers:
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
